version: '3'

services:
    nginx:
        image: nginx:1.17.10
        container_name: nginx
        depends_on:
            - cafe-frontend
            - cafe-backend
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            # - ./certs:/etc/nginx/certs
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        ports:
            - 80:80 #http
            - 443:443 #https
        command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

    cafe-frontend:
        image: cafe-frontend
        container_name: cafe-frontend
        build:
            context: ./cafe-frontend
        depends_on:
            - cafe-backend
        ports:
            - 3000:80
    cafe-backend:
        image: cafe-backend
        container_name: cafe-backend
        build:
            context: ./cafe-backend
        ports:
            - 3001:3001
    certbot:
        image: certbot/certbot
        volumes:
            - ./data/certbot/conf:/etc/letsencrypt
            - ./data/certbot/www:/var/www/certbot
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
